[build.env]
passthrough = ["RUSTFLAGS", "CARGO_TARGET_ARMV6_UNKNOWN_LINUX_MUSLEABIHF_MUSL_LIBC"]

[target.armv6-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/armv6-unknown-linux-musleabihf:latest"

[build]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt-get install -y libc6-dev-armhf crossbuild-essential-armhf"
]
